### PR TITLE
docs: added content for bus-factor + technical fork (EN + ZH)

### PR DESCRIPTION
**Pull request by Neilblaze**
## Description

Added the `Bus Factor` section into the [metrics](https://open-digger.cn/en/docs/user_docs/metrics) section. I've tried to preserve the quality of content by taking references from the existing ones (e.g. [Technical Fork](https://open-digger.cn/en/docs/user_docs/metrics/technical_fork)). ~~Do note that the Chinese version is [yet to be translated](https://opendigger.slack.com/archives/C076PCS77GQ/p1720025729250789), so once this is approved, I'll push in the changes for `CN`/`ZH` variant.~~

**UPDATE (04.07.24)** → Added the Chinese (`CN` / `ZH`) translation of both **`Bus Factor`** & **`Technical Fork`** 🎉 

🦄 Tested on local, build running successfully. PR is ready to be merged!

> Ref : [Slack Discussion](https://opendigger.slack.com/archives/C076PCS77GQ/p1719930249855619)  /  cc: @Peng99999 
○ **Partially resolves** #24

### Before submitting the PR, please take the following into consideration
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. If you don't have an issue, please create one.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems it solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is upto date with the `main` branch.

### CODE REVIEW

**Comment by Neilblaze** [comment]
> 🪧The website for this PR is deployed at https://open-digger.cn/pull_25/

@peng99999 the correct preview link is [this](https://open-digger.cn/pull_25/docs/user_docs/metrics/bus_factor).

**Comment by Peng99999** [comment]
@Neilblaze Well done! You can use translation software first (such as ChatGPT). If any modifications are needed in the Chinese documents, we will handle some of the language adjustments (polishing) ourselves afterwards.

**Comment by Neilblaze** [comment]
@Peng99999 ptal

**Comment by frank-zsy** [comment]
@Neilblaze I found that if we do not modify the base URL config in the config file, the redirections are broken in the preview website both yours and with 'preview` command. Is that right?

**Comment by frank-zsy** [comment]
@Neilblaze The workflow has been fixed. Right now, PR preview website will have a correct base URL to make sure all the relative links in the preview website are properly set. In order to make it take effect, I need to rebase and push back in this PR~

**Comment by Neilblaze** [comment]
> @Neilblaze I found that if we do not modify the base URL config in the config file, the redirections are broken in the preview website both yours and with 'preview` command. Is that right?

@frank-zsy Yes, exactly! That's the root reason. I was planning to raise a PR, but I'm glad that you fixed it 😄

**Comment by Neilblaze** [comment]
@frank-zsy, @Peng99999 can we get this merged so that I can start working on adding new metrics :)

**Comment by Peng99999** [comment]
@Neilblaze There are several places where the translation would be better as follows: "Bus factor" translated to "巴士因子"; "Technical Fork" translated to "技术分支".

**Comment by frank-zsy** [comment]
@Peng99999 Since @Neilblaze do not know Chinese, I think we should help with the Chinese part. I will work on this PR about the Chinese part then we can merge this PR.

**Comment by Neilblaze** [comment]
@frank-zsy That'd be extremely helpful, meanwhile as an update from my end, I've already started on [this](https://opendigger.slack.com/archives/C076PCS77GQ/p1720217476738709). Will ship a PR once done :)

**Comment by frank-zsy** [comment]
The PR now LGTM. Thanks for the docs. And I think ChatGPT is really good in translation~

**Pull request merged**
