### PR TITLE
docs: add multiple new CHAOSS metrics (EN + ZH)

### PR DESCRIPTION
**Pull request by Neilblaze**
## Description

Added new **CHAOSS** metrics (both `EN` & `ZH`), for the following :

- New Contributors
- Change Request(s) Reviews
- Change Requests Accepted
- Change Requests Age
- Change Requests Open
- Change Requests Resolution Duration
- Change Requests Response Time

[**Update 11-09-24**]: Refactored default views and added collapsibles. 

🦄 Tested on local, build running successfully!

cc: @Peng99999, @frank-zsy  /  **Partially resolves** #24

### Before submitting the PR, please take the following into consideration
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. If you don't have an issue, please create one.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems it solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is upto date with the `main` branch.

### CODE REVIEW

**Comment by frank-zsy** [comment]
@Neilblaze Sorry that I have multiple lectures this week, I will come back to this PR later.

**Comment by Neilblaze** [comment]
Sounds good!

**Comment by frank-zsy** [comment]
I think it is really confusing to have so many metrics listed in a single category. Could we add another level to the metrics. Like:

- OpenRank
- Activity
- General
  - Stars
  - Forks
- Developers
  - Active contributors
  - New contributors
  - Inactive contributors
  - Activity dates and times
- Issues
  - Issues new
  - Issues closed
  - Issues age
  - Issue comments
  - Issue response time
  - Issue resolution duration
- Changes requests
  - just like issue...

Do you think this will help users to understand?

**Comment by Neilblaze** [comment]
> Do you think this will help users to understand?

@frank-zsy I had this concern while I was working on this, and you're right, we can surely optimize the view. But here's the catch, (prolly I'm nitpicking) if I do so, then the changes will be reflected holistically across the table, and since we're introducing a new column, a few rows shall remain empty, which I guess is fine 🤔 (or might look confusing, idk)

I'll need to reiterate the changes in a *new commit* and link it to this PR, so just in case the new one (new commit with all the updated changes) looks bad, we can just simply reject that one, & proceed with the parent commit ([`2377c79`](https://github.com/X-lab2017/open-digger-website/pull/31/commits/2377c798923166fd728023f364c3f37fe4fab165)) itself.

**Comment by frank-zsy** [comment]
I think it's fine to make the change, actually I think we do not really need the table in introduction page after we have detailed metrics description in each page. We can remove the table and refer to metrics index page instead. WDYT

**Comment by Neilblaze** [comment]
> I think it's fine to make the change, actually I think we do not really need the table in introduction page after we have detailed metrics description in each page. We can remove the table and refer to metrics index page instead. WDYT

Personally, I feel that the table is an important part of the entire docs ecosystem since it acts as an index to every metrics. But sure, we can remove that. Or what I propose is we can make it modular and keep each respective section (say, `Activity`, `Developers`, `Issues`, etc.) as subsections of the primary table itself, isolated into a collapsible component, like this 👇🏼 

image 

This should in fact represent the same data but in a more convenient order, saving spaces across the page. Thoughts?

**Comment by frank-zsy** [comment]
That looks really cool!

**Comment by frank-zsy** [comment]
@Neilblaze Sorry, since I add a warning banner to preview deploy, I need to sync this PR with master branch but I miss operate with `rebase` rather than `pull`, so I need to force push back.

**Comment by Neilblaze** [comment]
> @Neilblaze Sorry, since I add a warning banner to preview deploy, I need to sync this PR with master branch but I miss operate with `rebase` rather than `pull`, so I need to force push back.

No worries, I've pulled in the changes. It's on the work, I'll notify once I'm done with [this](https://github.com/X-lab2017/open-digger-website/pull/31#issuecomment-2293475616) :)

**Comment by Neilblaze** [comment]
@frank-zsy , @Peng99999 😎 

ScreenRec

We can get this one merged, while in the background I'll work on the `EN` variant, and will create a PR once I'm done with that 😄

**Comment by Peng99999** [comment]
> @frank-zsy , @Peng99999 😎
> 
> ScreenRec [ ScreenRec ](https://private-user-images.githubusercontent.com/48355572/366583653-03a44f8d-e26c-4b9c-b69c-e7d0c47ba727.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDk1NjEsIm5iZiI6MTcyNjEwOTI2MSwicGF0aCI6Ii80ODM1NTU3Mi8zNjY1ODM2NTMtMDNhNDRmOGQtZTI2Yy00YjljLWI2OWMtZTdkMGM0N2JhNzI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyNDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzI0MzFhMGU5OTZlZDlkMDEwYjNkNWY5ZDNmN2NjZGVlZjMyMmQ2NjgwZmRhMjNiZjIzZTk1MTE4YjM3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h8olQTihuC0yyxh9TBwMK1WFnIeKEN2iNeRo-pxh9Q4) [ ](https://private-user-images.githubusercontent.com/48355572/366583653-03a44f8d-e26c-4b9c-b69c-e7d0c47ba727.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDk1NjEsIm5iZiI6MTcyNjEwOTI2MSwicGF0aCI6Ii80ODM1NTU3Mi8zNjY1ODM2NTMtMDNhNDRmOGQtZTI2Yy00YjljLWI2OWMtZTdkMGM0N2JhNzI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyNDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzI0MzFhMGU5OTZlZDlkMDEwYjNkNWY5ZDNmN2NjZGVlZjMyMmQ2NjgwZmRhMjNiZjIzZTk1MTE4YjM3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h8olQTihuC0yyxh9TBwMK1WFnIeKEN2iNeRo-pxh9Q4)
> 
> We can get this one merged, while in the background I'll work on the `EN` variant, and will create a PR once I'm done with that 😄

so cool！

**Comment by Neilblaze** [comment]
@frank-zsy just a heads up, I've noticed an overflow of text in the banner 👇🏼 

ScrRec

**Comment by frank-zsy** [comment]
> @frank-zsy just a heads up, I've noticed an overflow of text in the _**warning banner**_ 👇🏼
> 
> ScrRec

Yes, thanks, the banner should consider mobile layout. Fortunately this is just a preview deploy for PRs, nothing will be affected in production. I will look into how to fix this.

**Comment by frank-zsy** [comment]
@Neilblaze So this PR contains English and Chinese version of new metrics along with the new README menu in Chinese version, am I right?

BTW, the banner height has been fixed.

**Comment by Neilblaze** [comment]
@frank-zsy yep, correct!

**Comment by Neilblaze** [comment]
I'll ship the EN variant (which is pending) in 2 days, as soon as I'm done with my mid-sem exams 😅

**Comment by frank-zsy** [comment]
@Neilblaze No hurries, I will review and add more commits to this PR, it may change the content of the intro part.

**Comment by frank-zsy** [comment]
In this PR, I would like to update the metrics structure in the intro part as follow:

- OpenRank
  - Repo global OpenRank
  - Developer global OpenRank
  - Repo community OpenRank
  - Developer community OpenRank
- Statistics
  - Activity
  - Stars
  - Technical forks
  - Attention
  - Activity dates and times
- Developers
  - New contributors
  - Contributors
  - Inactive contributors
  - Participants
  - Bus factor
- Issues
  - Issues new
  - Issues closed
  - Issue comments
  - Issue response time
  - Issue resolution duration
  - Issue age 
- Change requests
  - Change requests
  - Change requests accepted
  - Change request reviews
  - Change request response time
  - Change request resolution duration
  - Change request age
  - Code change lines

In this structure, there will be only 5 top levels which will make the doc much cleaner.

**Comment by Neilblaze** [comment]
@frank-zsy That'll be awesome, and thanks for the help! 😃 
I feel the order (which you proposed) seems much better in terms of interpretability for anyone, be it a layman or an experienced user, so thanks again for the heads up!

**Comment by frank-zsy** [comment]
@Neilblaze I updated the intro doc and also the sidebar of docs part to fit the category. The categories are collapsed except OpenRank in intro doc and sidebar. Can you check the content and the links in the PR.

I think there are still some metrics missing related to issues and which from X-lab.

**Comment by Neilblaze** [comment]
> @Neilblaze I updated the intro doc and also the sidebar of docs part to fit the category. The categories are collapsed except OpenRank in intro doc and sidebar. Can you check the content and the links in the PR.
> 

Sure thing, I'll take a look and try to get things up and running. I'll also give a dry run for spell-check to ensure there's no typo.

> I think there are still some metrics missing related to issues and which from X-lab.

Regarding the metrics related to issues, it's nearly done, and for the `x-lab`, I intentionally kept it on hold (till now), [because](https://github.com/X-lab2017/open-digger-website/pull/28#issuecomment-2224378835) I think it might require your guidance :)

**Comment by frank-zsy** [comment]
@Neilblaze Yes, I will add the X-lab metrics. And actually issues and pull requests almost share the same metrics, we should manage how to present that.

**Comment by Neilblaze** [comment]
> ... actually issues and pull requests almost share the same metrics, we should manage how to present that.

@frank-zsy yes, I noticed that. One way can be multiplexing both under a common name and keeping individual info under that 🤔 

I'll try to come up with something (better) in the meantime.

**Comment by frank-zsy** [comment]
I would like to merge this PR first and raise PRs if there is anything to modify later.

**Comment by Neilblaze** [comment]
↪️ Continued in #45

**Pull request merged**
