### PR TITLE
feat: add a search input component for other pages

### LINKED ISSUE #32: [Feature] A search component for the website
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

We need a search input component to list all matched repos or users name when developers search like in Playground page.`

### Proposed solution (optional)

OpenDigger export data for about 370000 repos, the list is [here](https://oss.x-lab.info/open_digger/repo_list.csv), this is a repo list with csv format and update once a month.

We can have a component download and parse the result, then store it in the local storage and search with some libs like [fuse.js](https://www.fusejs.io/demo.html). This will help to enhance the search input box.

### PR DESCRIPTION
**Pull request by frank-zsy**
## Description

This a general search component for other pages. This component supports:

- Different platforms.
- Different types(repo or user).
- Different metrics.
- Full search with repo names and user logins without case sensitive.

And also replace the search component in the Playground page.

## Resolved issues

Closes #32 

### Before submitting the PR, please take the following into consideration
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. If you don't have an issue, please create one.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems it solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is upto date with the `main` branch.

### CODE REVIEW

**Comment by frank-zsy** [comment]
@Neilblaze Could you please review this PR, this PR contains a React component to search repo and user names exported by OpenDigger to optimize the user experience in Playground and other future pages.

**Comment by Neilblaze** [comment]
> @Neilblaze Could you please review this PR, this PR contains a React component to search repo and user names exported by OpenDigger to optimize the user experience in Playground and other future pages.

@frank-zsy Sorry for the late reply, I was traveling... but hopefully return by this weekend, will take a look asap :)

**Comment by frank-zsy** [comment]
> @frank-zsy Sorry for the late reply, I was traveling... but hopefully return by this weekend, will take a look asap :)

No worry, I think the functionality looks alright now, I may merge this PR first and you can take a look at the code when you are free.

**Pull request merged**
