### PR TITLE
docs: add multiple new metrics (EN + ZH)

### PR DESCRIPTION
**Pull request by Neilblaze**
## Description

Fixed typo in `Bus Factor`, updated dependencies to latest & added new metrics (both `EN` & `ZH`), for the following, mentioned below (includes updates from `20/04/2024`) :

- Activity Details
- Activity Dates and Times
- Inactive Contributors
- Issue Resolution Duration
- Issue Response Time

🦄 Tested on local, build running successfully!

> Ref : [Slack Discussion](https://opendigger.slack.com/archives/C076PCS77GQ/p1720546005423529)  /  cc: @Peng99999, @frank-zsy  
○ **Partially resolves** #24

### Before submitting the PR, please take the following into consideration
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. If you don't have an issue, please create one.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems it solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is upto date with the `main` branch.

### CODE REVIEW

**Comment by frank-zsy** [comment]
Thanks for the docs. I will update the Chinese version.

I think you should start with CHAOSS statistical metrics since they are quite easy and have CHAOSS documentations as reference.

Metrics from X-lab are almost complex metrics involves calculation or even graph data structure, so we can add them at last.

**Comment by frank-zsy** [comment]
Actually time period related metrics like resolution duration and response time are also tricky. So these metrics will involve deep collaboration with me.

**Comment by Neilblaze** [comment]
> Thanks for the docs. I will update the Chinese version.

Sounds good, thank you! 😄 

> I think you should start with CHAOSS statistical metrics since they are quite easy and have CHAOSS documentations as reference.

I see, thanks for the heads up! Alright, I'll prioritize CHAOSS metrics first, and once those are completed, I'll start digging into the X-lab metrics with your guidance.

> Metrics from X-lab are almost complex metrics involves calculation or even graph data structure, so we can add them at last.

Got it!

**Comment by frank-zsy** [comment]
@Neilblaze I add LaTeX support and modify the docs, could you modify the English version due to my modification? Especially activity metrics. And activity and activity details are both included in the activity part now.

And I think we can remove the English name of each metrics in the Chinese doc titles and we do not need to translate Issue and PR.

**Comment by Neilblaze** [comment]
Yessir, I'll do that :)

**Comment by frank-zsy** [comment]
This PR LGTM now. Thanks for the great work!

I will merge this PR now and further more:

- I think change request response time and resolution duration could be merged with issue corresponding metrics.
- Pls feel free to raise PR and discuss on GitHub, since Slack is not quite stable in China, I can only receive the notification but can not retrieve the messages smoothly. Sorry for that.

**Comment by Neilblaze** [comment]
@frank-zsy Thanks for merging the PR! 😃 

> I think change request response time and resolution duration could be merged with issue corresponding metrics.

Sure thing! In the next PR, I'll make sure to do this.

> Pls feel free to raise PR and discuss on GitHub, since Slack is not quite stable in China, I can only receive the notification but can not retrieve the messages smoothly. Sorry for that.

Thanks for the heads up! I understand that Slack isn't that accessible in China, so I do recommend enabling [**GitHub Discussions**](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) in this repo, which will be very helpful for everyone.

Thanks :)

**Comment by Neilblaze** [comment]
@frank-zsy Also, for this:

image


- Change requests (Open PR)
- Change requests reviews
- Change request response time
- Change request resolution duration
- Change request age

Should I create separate metrics page (individual pages / each) for each **OR** create one `separate metrics` section and under that keep these nested, which will look something like this:

* Change Requests
    * Open PR
    * Reviews
    * Response Time
    * Resolution Duration
    * Age

**Comment by frank-zsy** [comment]
> Thanks for the heads up! I understand that Slack isn't that accessible in China, so I do recommend enabling [**GitHub Discussions**](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) in this repo, which will be very helpful for everyone.

Of course we can enable discussion for this repo, however I don't really fond of this function because discussion events can not be collected by GitHub events API.

> Should I create separate metrics page (individual pages / each) for each **OR** create one `separate metrics` section and under that keep these nested, which will look something like this:

I think group change request and issue metrics to a category is cool and helps to organize the catalog and make it much clearer.

**Comment by Neilblaze** [comment]
@frank-zsy UPDATE:

For this, I tried to keep the "Issues" section standalone and then keep two inter-sections "`new`" and "`closed`", but I feel that is making the entire table ugly 😅 

image

So, I'm keeping it as it is, plus I feel it makes things easier for people to perform individual search on different topics. Rest aside, if anyone wants something specific, they can use the search-bar. ^_^

Thoughts?

**Comment by Neilblaze** [comment]
So for now, I'll start shipping out PRs for the rest of the metrics, keeping the priority on `CHAOSS` first, then once those are done, I can move into `x-lab` ones, where I'll hopefully require some help :)

**Pull request merged**
