### PR TITLE
docs: add CHAOSS metrics (EN + ZH) + refactoring

### PR DESCRIPTION
**Pull request by Neilblaze**
## Description

Added new **CHAOSS** metrics (both `EN` & `ZH`), fixed links, and minor bugs. 

🦄 Tested on local, build running successfully!

cc: @Peng99999, @frank-zsy  /  **Partially resolves** #24

### Before submitting the PR, please take the following into consideration
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. If you don't have an issue, please create one.
- [x] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [x] The description should clearly illustrate what problems it solves.
- [x] Ensure that the commit messages follow our guidelines.
- [x] Resolve merge conflicts (if any).
- [x] Make sure that the current branch is upto date with the `main` branch.

### CODE REVIEW

**Comment by frank-zsy** [comment]
Really amazing, you even change the CHAOSS URL to zh-CN for ZH language. I will modify the Chinese part.

**Comment by frank-zsy** [comment]
@Neilblaze I will merge the PR and congrats on finishing your OSPP task~ I will add X-lab metrics part later.

**Comment by Neilblaze** [comment]
> I will merge the PR and congrats on finishing your OSPP task~ I will add X-lab metrics part later.

Thank you @frank-zsy! 🥳  
Also, just to let you know, I received an email from OSPP (a few days ago) that I must submit my Final Project Report by the 30th instant (I think [彭佳恒](https://github.com/Peng99999) also referred to the same on Slack). So, I'll start working on it now and will let you know if I need anything from you.

cc: @Peng99999

**Comment by Peng99999** [comment]
> > I will merge the PR and congrats on finishing your OSPP task~ I will add X-lab metrics part later.
> 
> Thank you @frank-zsy! 🥳 Also, just to let you know, I received an email from OSPP (a few days ago) that I must submit my Final Project Report by the 30th instant (I think [彭佳恒](https://github.com/Peng99999) also referred to the same on [Slack](https://opendigger.slack.com/archives/C076PCS77GQ/p1726057826908509)). So, I'll start working on it now and will let you know if I need anything from you.
> 
> cc: @Peng99999

yeah, I have received the same email. Please don’t forget to write the OSPP final project report😄

**Comment by Neilblaze** [comment]
@frank-zsy , @Peng99999 I've prepared the _**Final Project Report**_ & it's accessible 👉🏼  " [**here**](https://docs.google.com/document/d/1OE9YTTYBPEQ4AXyRn_PHlZ2tvlcDltHTh1jcBGBHfwQ/edit?usp=sharing) "  
Feedbacks are greatly appreciated! 🙏🏼 

Once I receive the green signal, I'll submit! 😄

**Comment by frank-zsy** [comment]
@Neilblaze Great report. There are several things:

- I would like to use `open source` rather than `open-source` as an adj.
- I think you can add a table about the `contributions tracker part`, like besides 4 PRs merged, there are 32 commits and 96 discussions, along with 2387 lines added. The numbers are really impressive.

**Comment by Neilblaze** [comment]
@frank-zsy Noted! ✅
Thanks for the review, I will update the report & submit it by tomorrow! 😃

**Comment by Peng99999** [comment]
@Neilblaze I have seen the final report you submitted on the OSPP website. Once the review period begins (Oct. 1), I will approve your final report. The website looks more refined and visually appealing now, thank you for making a significant contribution. 👍👏  We also welcome you to continue contributing in the future.😃

**Comment by Neilblaze** [comment]
@Peng99999 Thanks for the positive feedback, really appreciate that! 
And to your point, yes, absolutely! I'd love to continue contributing to the OpenDigger website and improve it further! 😄

**Pull request merged**
