### PR TITLE
feat: Improved the issue where the GitHub icon pointed to only the "website" repository.

### LINKED ISSUE #46: Does the repository that the website is directed to need improvement?
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

image

Clicking on this icon on the website will redirect to the repository of Opendigger instead of  opendigger-website. 

There is a common scenario：👉 someone is browsing this website and then wants to check out the code of the website's repository, or they want to contribute to the website. So, they click the GitHub icon in the upper-right corner, but it redirects them to the Opendigger repository. Could this be misleading?

Should we add a link to redirect to the repository of opendigger-website?

### Proposed solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by Peng99999**
## Description

Improved the issue (#46) where the GitHub icon pointed to only the "website" repository. It has now been changed to a dropdown, allowing users to choose between accessing "opendigger" or "opendigger-website."

image

## Resolved issues

Closes #46

### CODE REVIEW

**Comment by frank-zsy** [comment]
It makes sense to use dropdown item here. I commit to:
- It should be `GitHub` rather than `Github`
- For links, we should remove `GitHub` and redundant words to keep it neat
- If we do not need the icon, we could just remove the css rather than comment them

But still, I think the icon is much better looking than `GitHub` plain text, but I can not figure out how to add a dropdown list to an icon in the navbar.

@Neilblaze WDYT? Is there any way to add link list to an icon and make it a dropdown item?

**Comment by Neilblaze** [comment]
@frank-zsy, @Peng99999 I don't have edit/write privileges (since I'm a non-member of [x-lab2017](https://github.com/X-lab2017/)), so I'm linking my reviews/suggestions herewith. Just replace the current content for `docusaurus.config.ts` and `custom.css` with my content, which can be found → [**here**](https://github.com/Neilblaze/open-digger/commit/4bb14464e075d34b1381abafa713e84a19eb9895) .

Preview:

**Landscape Preview**            |  **Mobile Preview**
:-------------------------:|:-------------------------:
prev1  |  prev2

**Comment by Neilblaze** [comment]
Btw, now that I've already mentioned it, I'm really curious to know how an existing contributor can be a part of `X-lab2017` GitHub org? 🤔

**Comment by Peng99999** [comment]
> @frank-zsy, @Peng99999 I don't have edit/write privileges (since I'm a non-member of [x-lab2017](https://github.com/X-lab2017/)), so I'm linking my reviews/suggestions herewith. Just replace the current content for `docusaurus.config.ts` and `custom.css` with my content, which can be found → [**here**](https://github.com/Neilblaze/open-digger/commit/4bb14464e075d34b1381abafa713e84a19eb9895) .
> 
> Preview:
> 
> **Landscape Preview**	**Mobile Preview**
> prev1	prev2

Thank you, @Neilblaze , for the great solution.😄  @frank-zsy, Can we invite @Neilblaze to join in X-lab2017 GitHub org?

**Comment by frank-zsy** [comment]
@Neilblaze Great, if you are interested in our work, I can invite you as a member of X-lab and committer of this repo.

**Comment by Neilblaze** [comment]
@frank-zsy Sure, would love to be a part of the family! 😃

**Comment by frank-zsy** [comment]
@Neilblaze Invitation sent. Welcome to X-lab and OpenDigger~~

**Pull request merged**
